sudo: required
services:
  - docker

before_install:
  - docker build -t eakmv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run eakmv/react-test npm test -- --coverage

after_success:
  - docker build -t eakmv/multi-client ./client
  - docker build -t eakmv/multi-nginx ./nginx
  - docker build -t eakmv/multi-server ./server
  - docker build -t eakmv/multi-worker ./worker

